### ISSUE TITLE
!! This project needs a name !!

### ISSUE THREAD

**Issue by HerrZatacke** [HerrZatacke/custom-camera-rom#1]
If you have any good ideas, add them in the replys to this issue.

**Comment by HerrZatacke** [comment]
My working title was "GB Foto Studio"... 
Maybe the english "GB Photo Studio" could work
Also interesting parts for the  name could be:
* 2bit
* pixel
* studio
* laboratory

**Comment by HerrZatacke** [comment]
My working title was "GB Foto Studio"...
Maybe the english "GB Photo Studio" could work
Also interesting parts for the name could be:

2bit
pixel
studio
laboratory
camera

**Comment by zenaro147** [comment]
GB Pocket Studio 😁

(Actually I really like the GBPS acronym)

**Comment by LordRembo** [comment]
Photo Pixel
Photo PX
Photo DeLux
GB PX
GB Photo
GB Photo DeLux

**Comment by Raphael-Boichot** [comment]
No camera ! (it's the name)

**Comment by LordRembo** [comment]
GB Photo DLX

**Comment by N3rd1n5id3** [comment]
GB Camera Pro

**Comment by HerrZatacke** [comment]
Drumroll please... 🥁
...
...
The full name of this project is now:
...
### `2bit PXLR Studio`
...
🎉🥳
