### ISSUE TITLE
Press SELECT to come back to sensor initial settings

### ISSUE THREAD

**Issue by Raphael-Boichot** [HerrZatacke/custom-camera-rom#11]
That's the idea. Perhaps cycling between a limited number of presets with the same button.

**Comment by HerrZatacke** [comment]
Probably related to #9 
Maybe it will also make sense to have different shooting modes where left<->right cycle through different sets of settings.

**Comment by HerrZatacke** [comment]
#26 
`start`+ `select` resets sensor settings now
