### ISSUE TITLE
toggle option for default settings

### ISSUE THREAD

**Issue by bcoyle** [HerrZatacke/custom-camera-rom#26]
have option to either save settings between power cycles or reset to default.

mom finding more often I want defaults at start up because I’ve gone down a rabbit hole with tweaking things and don’t know what I did.

**Comment by HerrZatacke** [comment]
What about adding it so you could push `start+select` inside the manual shoot mode?

**Comment by bcoyle** [comment]
That would certainly be helpful!

**Comment by HerrZatacke** [comment]
#11
`start`+ `select` resets sensor settings now
