### ISSUE TITLE
Pre-compiled rom

### ISSUE THREAD

**Issue by epbarger** [HerrZatacke/custom-camera-rom#3]
This is a super cool project! If it's possible, it would be nice to use the "Releases" feature of github to provide a download for a pre-compiled rom file

**Comment by HerrZatacke** [comment]
Currently I'm posting the compiled ROM in the [Game Boy Camera Club discord](https://discord.com/invite/C7WFJHG) in the `#custom-camera-rom` channel.
But adding releases is definitely on my near-future list!

**Comment by HerrZatacke** [comment]
Releases are now automatically generated and listed on the [releases page](https://github.com/HerrZatacke/custom-camera-rom/releases)
